# Autogenerated wrapper script for tree_sitter_css_jll for x86_64-apple-darwin
export libtreesitter_css

JLLWrappers.@generate_wrapper_header("tree_sitter_css")
JLLWrappers.@declare_library_product(libtreesitter_css, "@rpath/libtreesitter_css.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libtreesitter_css,
        "lib/libtreesitter_css.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
